# CC = g++
# CFLAGS = -std=c++11 -Wall
# LIBS = -I include -L lib -l SDL2-2.0.0

# SRCS = sphere_sdl.cpp
# OBJS = $(SRCS:.cpp=.o)
# EXECUTABLE = program

# .PHONY: all clean

# all: $(EXECUTABLE)

# $(EXECUTABLE): $(OBJS)
# 	$(CC) $(CFLAGS) $(OBJS) -o $(EXECUTABLE) $(LIBS)

# .cpp.o:
# 	$(CC) $(CFLAGS) -c $< -o $@

# clean:
# 	rm -f $(OBJS) $(EXECUTABLE)
game:
	g++ sphere_sdl.cpp -o play -I include -L lib -l SDL2-2.0.0 -lGL